---
- name: Ensure PostgreSQL languages are present.
  postgresql_lang:
    lang: "{{ item.lang }}"
    cascade: "{{ item.cascade | default(omit) }}"
    db: "{{ item.db | default(omit) }}"
    login_host: "{{ docker_postgres_host}}"
    login_password: "{{ docker_postgres_password }}"
    login_user: "{{ docker_postgres_user }}"
    trust: "{{ item.trust | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ docker_postgres_languages }}"
